### ISSUE TITLE
Observations limited to Int64?

### ISSUE THREAD

**Issue by ermueller2000** [ericchiang/ANN.jl#2]
Hi Eric,

I'm playing around with your ANN package and followed the readme directions but got an error that the appropriate fit method couldn't be found.  I traced it to the fact that I was passing in a set of Float64s to fit!, when it's expecting a vector of Int64s.  Is there a work-around for this?  Thanks!
 Eric

fit!(ann::ArtificialNeuralNetwork,
              x::Matrix{Float64},
              y::Vector{Int64};
              epochs::Int64 = 5,
              alpha::Float64 = 0.1,
              lambda::Float64 = 0.1)

**Comment by ericchiang** [comment]
This particular neural network is a classification algorithm not a regressions algorithm. The target vector (y) is therefore `Int64`, a discrete datatype, rather than `Float64` because it should contain classes not continuous variables.

This has actually been brought up before on this repo: https://github.com/EricChiang/ANN.jl/issues/1

So yeah, I'd advise typecasting your y vector. It should contain classes anyway. Though, maybe it should be able to accept an array of strings as well?

**Comment by ermueller2000** [comment]
Thanks for the explanation, and sorry for the duplicative issue (I'm rather
new to github).
 Eric
